[package]
name = "glorious-rusty-rest-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "9.3.0"
rocket = { version = "0.5.0", features = ["json"] }